/*
 * multiGame.cpp
 *
 *  Created on: Aug 1, 2014
 *      Author: brandon
 */

#include <iostream>
#include <string>
#include <vector>

#include "SwansonLibs/swansonUtils.hpp"

#include "SwansonObjects/ArgReader.hpp"
#include "SwansonObjects/menu.hpp"
#include "SwansonObjects/Dictionary.hpp"
#include "SwansonObjects/PreFabDictionary.hpp"

#include "NumberGuess.hpp"
#include "wordGuess.hpp"
#include "phraseGuess.hpp"

#include "GameClass.hpp"

using namespace std;

//command line arguments
const string SIMPLE_MODE = "-s";

//Output Strings
const string INTRO = "Welcome to the Game Console";
const string AGAIN = "Would you like to play again";

//global variables
NumberGuess *myNumberGame;
WordGuess *myWordGame;
PhraseGuess *myPhraseGame;
ListItem *DifficultyChooser;
bool ComputerGenerated = true;
Dictionary myDict;

//difficulty
const string EASY = "Easy";
const string MED = "Medium";
const string HARD = "Hard";
string DifficultySelected = MED;

const int EASY_GUESS = 7;
const int MED_GUESS = 6;
const int HARD_GUESS = 5;

const int EASY_NUMBER = 20;
const int MED_NUMBER = 50;
const int HARD_NUMBER = 100;

const int EASY_WORD = 5;
const int MED_WORD = 7;
const int HARD_WORD = 8;

//function prototypes
void PlayNumberGuess ();
void PlayWordGuess ();
void PlayPhraseGuess ();
void ChangeDifficulty ();
void SetDictionary ( int maxLength );

int main ( int argc , char* argv[] ) {

   const int MAX_WORD_LENGTH = 7;
   Menu myMenu( INTRO );

   ///process command line arguments//////////////
   //args passed to ARGinAttor
   ARGinAttor myARGinAttor( argc , argv );

   swansonUtil::SeedRandom();

   //instance a dictionary
   SetDictionary( MED_WORD );

   //instance 3 games
   myNumberGame = new NumberGuess;
   myWordGame = new WordGuess( myDict );
   myPhraseGame = new PhraseGuess( myDict );

   //check Arginators arguement set<string> for -s SIMPLE MODE
   if ( myARGinAttor.ArgumentPassedIn( SIMPLE_MODE ) ) {
      myMenu.setClear( swansonUtil::HackClearScreen );
      myNumberGame->SetClearScreen( swansonUtil::HackClearScreen );
      myWordGame->SetClearScreen( swansonUtil::HackClearScreen );
      myPhraseGame->SetClearScreen( swansonUtil::HackClearScreen );
   }

   ///filling menu
   myMenu.addItem( new GoItem( PlayNumberGuess , "NumberGuess" , "" , AGAIN ) );
   myMenu.addItem( new GoItem( PlayWordGuess , "Word Guess" , "" , AGAIN ) );
   myMenu.addItem(
         new GoItem( PlayPhraseGuess , "Phrase Guess" , "" , AGAIN ) );
   myMenu.addItem(
         new BoolItem( ComputerGenerated , "Secret is generated by" ,
               "Computer" , "Human" ) );

   //dificulty setting
   vector<string> difficulties;
   difficulties.push_back( EASY );
   difficulties.push_back( MED );
   difficulties.push_back( HARD );
   DifficultyChooser = new ListItem( difficulties , "Difficulty" , 1 );
   myMenu.addItem( DifficultyChooser );

   myMenu.showMenu();

}

//function definitions
void PlayNumberGuess () {
   myNumberGame->SetComputerGeneratedSecret( ComputerGenerated );
   if ( DifficultySelected != DifficultyChooser->GetSelection() )
      ChangeDifficulty();
   myNumberGame->PlayGame();
}
void PlayWordGuess () {
   myWordGame->SetComputerGeneratedSecret( ComputerGenerated );
   if ( DifficultySelected != DifficultyChooser->GetSelection() )
      ChangeDifficulty();
   myWordGame->PlayGame();
}
void PlayPhraseGuess () {
   myPhraseGame->SetComputerGeneratedSecret( ComputerGenerated );
   if ( DifficultySelected != DifficultyChooser->GetSelection() )
      ChangeDifficulty();
   myPhraseGame->PlayGame();
}

void ChangeDifficulty () {
   DifficultySelected = DifficultyChooser->GetSelection();

   if ( DifficultySelected == EASY ) {
      myNumberGame->SetMaxGuesses( EASY_GUESS );
      myWordGame->SetMaxGuesses( EASY_GUESS );
      myPhraseGame->SetMaxGuesses( EASY_GUESS );

      myNumberGame->SetNumRange( EASY_NUMBER );
      SetDictionary( EASY_WORD );
      myWordGame->SetDictionary( myDict );
      myPhraseGame->SetDictionary( myDict );
   } else if ( DifficultySelected == HARD ) {

      myNumberGame->SetMaxGuesses( HARD_GUESS );
      myWordGame->SetMaxGuesses( HARD_GUESS );
      myPhraseGame->SetMaxGuesses( HARD_GUESS );

      myNumberGame->SetNumRange( HARD_NUMBER );
      SetDictionary( HARD_WORD );
      myWordGame->SetDictionary( myDict );
      myPhraseGame->SetDictionary( myDict );

   } else if ( DifficultySelected == MED ) {

      myNumberGame->SetMaxGuesses( MED_GUESS );
      myWordGame->SetMaxGuesses( MED_NUMBER );
      myPhraseGame->SetMaxGuesses( MED_NUMBER );

      myNumberGame->SetNumRange( MED_NUMBER );
      SetDictionary( MED_WORD );
      myWordGame->SetDictionary( myDict );
      myPhraseGame->SetDictionary( myDict );
   }
}

void SetDictionary ( int maxLength ) {
   myDict = Dictionary( maxLength );
   if ( !myDict.Filled() )
      myDict = PreFabDict::UsePreFabDict();
}

